name: Run Python on PR Opened

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-review-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run review script
        run: python review.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
